vocs_platform_homepage:
    path:     /
    defaults: { _controller: VOCSPlatformBundle:Default:index }

vocs_platform_equipe:
    path: /equipe
    defaults: 
        _controller: VOCSPlatformBundle:Default:equipe

vocs_platform_connexion:
    path: /connexion
    defaults: 
        _controller: VOCSPlatformBundle:Default:connexion

vocs_platform_a_propos:
    path: /a_propos
    defaults: 
        _controller: VOCSPlatformBundle:Default:apropos
