VOCS\PlatformBundle\Entity\Classes:
    attributes:
        id:
            groups: ['classe', 'user', 'demand']
        name:
            groups: ['classe', 'demand']
        lists:
            groups: ['classe']
        users:
            groups: ['classe']


VOCS\PlatformBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'classe', 'demand']
        email:
            groups: ['user']
        firstname:
            groups: ['user', 'demand']
        surname:
            groups: ['user', 'demand']
        roles:
            groups: ['user', 'classe', 'demand']
        classes:
            groups: ['user']

VOCS\PlatformBundle\Entity\Lists:
    attributes:
        id:
            groups: ['list', 'classe']
        name:
            groups: ['list', 'classe']
        creationDate:
            groups: ['list']
        wordTrads:
            groups: ['list']

VOCS\PlatformBundle\Entity\WordTrad:
    attributes:
        id:
            groups: ['list', 'wordTrad']
        word:
            groups: ['list', 'wordTrad']
        trad:
            groups: ['list', 'wordTrad']

VOCS\PlatformBundle\Entity\Words:
    attributes:
        content:
            groups: ['list', 'wordTrad']
        language:
            groups: ['list', 'wordTrad']
        trads:
            groups: ['list', 'wordTrad']


VOCS\PlatformBundle\Entity\Schools:
    attributes:
        id:
            groups: ['school']
        nom:
            groups: ['school']
        cp:
            groups: ['school']



VOCS\PlatformBundle\Entity\Language:
    attributes:
        code:
            groups: ['list']

VOCS\PlatformBundle\Entity\Demands:
    attributes:
        userSend:
            groups: ['demand']
        userReceive:
            groups: ['demand']
        classe:
            groups: ['demand']




