VOCS\PlatformBundle\Entity\Classes:
    attributes:
        id:
            groups: ['classe', 'user']
        name:
            groups: ['classe']
        lists:
            groups: ['classe']
        users:
            groups: ['classe']


VOCS\PlatformBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'classe']
        email:
            groups: ['user']
        firstname:
            groups: ['user']
        surname:
            groups: ['user']
        roles:
            groups: ['user', 'classe']
        classes:
            groups: ['user']

VOCS\PlatformBundle\Entity\Lists:
    attributes:
        id:
            groups: ['list', 'classe']
        name:
            groups: ['list']
        creationDate:
            groups: ['list']
        wordTrads:
            groups: ['list']

VOCS\PlatformBundle\Entity\WordTrad:
    attributes:
        word:
            groups: ['list']
        trad:
            groups: ['list']

VOCS\PlatformBundle\Entity\Words:
    attributes:
        content:
            groups: ['list']
        language:
            groups: ['list']
        trads:
            groups: ['list']


VOCS\PlatformBundle\Entity\Schools:
    attributes:
        id:
            groups: ['school']
        nom:
            groups: ['school']
        cp:
            groups: ['school']



VOCS\PlatformBundle\Entity\Language:
    attributes:
        code:
            groups: ['list']



