VOCS\PlatformBundle\Entity\Classes:
    attributes:
        id:
            groups: ['classe', 'user']
        name:
            groups: ['classe']
        lists:
            groups: ['classe']
        users:
            groups: ['classe']


VOCS\PlatformBundle\Entity\User:
    attributes:
        id:
            groups: ['user', 'classe']
        email:
            groups: ['user']
        firstname:
            groups: ['user']
        surname:
            groups: ['user']
        roles:
            groups: ['user', 'classe']
        classes:
            groups: ['user']

VOCS\PlatformBundle\Entity\Lists:
    attributes:
        id:
            groups: ['list']
        name:
            groups: ['list']
        creationDate:
            groups: ['list']



VOCS\PlatformBundle\Entity\Schools:
    attributes:
        id:
            groups: ['school']
        nom:
            groups: ['school']
        cp:
            groups: ['school']

VOCS\PlatformBundle\Entity\ListsWords:
    attributes:
        id:
            groups: ['school']
        nom:
            groups: ['school']
        cp:
            groups: ['school']



